### ISSUE TITLE
Change the background color and draw a border box - using the container.

### ISSUE THREAD

**Issue by sunami09** [Multiprocessing-Muggles/The-Tribute-Website#4]
# From

![image](https://user-images.githubusercontent.com/66564001/163012430-75326014-b045-482e-8047-0ddb8c21b165.png)

# To This

![image](https://user-images.githubusercontent.com/66564001/163012507-abc9febe-75e2-4bda-af75-b4afda9a01a8.png)

* Background color code : #e5e5fd
* Border is 10px and color: rgb(4, 4, 37)

**Comment by lucalves** [comment]
Hi @sunami09, how are you?

I've found your project at [Good First Issues](https://goodfirstissues.com/) website!

I opened #7 to solve this Issue :)

**Comment by sunami09** [comment]
@lucalves Would you like to join this organization?

**Comment by lucalves** [comment]
@sunami09 At the moment I already have a few organizations that I contribute to.

But whenever possible I'll be contributing to your organization's projects, too! 😉

**Comment by sunami09** [comment]
Ok! Thank you for your contribution
