### ISSUE TITLE
There is a gap between the viewport and the container - remove it

### ISSUE THREAD

**Issue by sunami09** [Multiprocessing-Muggles/The-Tribute-Website#8]
# This

![image](https://user-images.githubusercontent.com/66564001/163064857-796f69d6-d7a9-4f7c-9dfa-fe1da55575b4.png)

**Comment by Alcadeus0** [comment]
Border and margin need to be set to zero for the body. That should solve the issue

**Comment by sunami09** [comment]
@Alcadeus0 would you like to work on this issue?

**Comment by Alcadeus0** [comment]
@sunami09 Yeah I'd like to work on it.

**Comment by sunami09** [comment]
Make a pull request. Remember to attach a screenshot of what you have chnaged

**Comment by Alcadeus0** [comment]
I've made a pull request. Let me know if everything is as expected.
